apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaler
  namespace: default
  labels:
    deploymentName: node-subscriber
spec:
  scaleTargetRef:
    deploymentName: node-subscriber
  minReplicaCount: 0
  cooldownPeriod:  10
  pollingInterval: 30
  triggers:
  - type: kafka
    metadata:
      topic: A
      bootstrapServers:  my-kafka.default.svc.cluster.local:9092
      consumerGroup: node-subscriber
      lagThreshold: '1'
